go compiler check descriptive error message
apptainer/apptainer pull request #1046
Opened 2023-01-30 20:55 UTC by simonleary-umass-edu

This is a continuation of [my last PR](https://github.com/apptainer/apptainer/pull/1045) which I broke while fumbling around with `git`.

2023-01-30 23:30 UTC, DrDaveD requested changes

2023-01-30 23:30 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +			break
The `break` is no longer needed now that there's no loop.

2023-01-30 23:30 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +		break
likewise here.

2023-01-30 23:30 UTC, DrDaveD commented on mlocal/scripts/check-min-go-version
> +}
Don't forget to pull the `exit 1` into this function.

2023-01-30 23:42 UTC, simonleary-umass-edu commented
Oops, I had fixed `exit 1` before but it got left behind when I was fumbling with git

2023-01-31 00:31 UTC, DrDaveD requested changes

2023-01-31 00:31 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +		gopth=`command -v $go`
This needs to be `go`, not `$go`.

2023-01-31 00:31 UTC, DrDaveD commented on mlocal/checks/basechecks.chk
> +		hstgo=`command -v $go`
Here too.

2023-01-31 03:38 UTC, DrDaveD approved these changes

2023-01-31 03:38 UTC, merged