App instances
apptainer/apptainer pull request #1125
Opened 2023-02-22 05:17 UTC by struktured

## Description of the Pull Request (PR):

Introduces an optional `--app` argument to the `apptainer instance start` command which will leverage
the `%appstart` section if it exists in the definition file to instantiate a particular app as a service. Eg.

````Console
apptainer instance start --app tail tailer.sif tailer
````

with definition file `tailer.def` containing:

```Yaml
%appstart tail
    tail -f /dev/null
```
will create a service called `tailer` which invokes the app `tail` that simply tails `/dev/null` until terminated.

Stopping the instance is the exact same as stopping any other apptainer instance. The app name is no longer necessary- only the instance name is required. For the above the invocation is

```Console
apptainer instance stop tailer
```
In addition to extending the e2e test, also updated the examples where appropriate to indicate the new functionality.

### This fixes or addresses the following GitHub issues:

 - Fixes #1118 

#### Before submitting a PR, make sure you have done the following:

- [x] Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- [ ] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
  - [x] e2e imageverify test extended to test `%appstart`
  - [ ] TODO: standard unit test?
- [x] Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- [x] Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

2023-02-22 05:20 UTC, struktured commented
Some notes before this is ready to merge:

 - I couldn't find documented the appropriate merge strategy- is squashing ok? Or is rebasing required, etc..
 - I am not certain I have sufficient test coverage. I modified the e2e image verify test but I think a pure unit test somewhere might make sense too. Open to guidance on how to add a good test.

2023-02-22 17:26 UTC, DrDaveD commented
Overall this contribution looks quite good to me.  We do need you to do `git commit -s` to indicate agreement with the DCO as detailed in CONTRIBUTING.md.

> Some notes before this is ready to merge:
> 
>     * I couldn't find documented the appropriate merge strategy- is squashing ok? Or is rebasing required, etc..

I prefer a single commit for things that are all related.  You might want to have a separate commit for removing the extra blanks you saw.  Each commit needs the `-s` option.  I would use `git reset HEAD^1` to back out each commit and then do `git push -f` to update the PR.

>     * I am not certain I have sufficient test coverage. I modified the e2e image verify test but I think a pure unit test somewhere might make sense too. Open to guidance on how to add a good test.

Just look for precedents for similar features.  If they have unit test coverage, add a similar unit test, otherwise don't bother, and let the e2e test cover it.

2023-03-06 19:46 UTC, DrDaveD requested changes
I'm sorry for the delay, I was away.  I approved the test runs and there's an [e2e test failure](https://github.com/apptainer/apptainer/actions/runs/4249539640/jobs/7593753494#step:10:3917) and [another set of 3](https://github.com/apptainer/apptainer/actions/runs/4249539640/jobs/7593753494#step:10:4040) just like the first.

2023-03-13 20:29 UTC, DrDaveD commented
@struktured can you please look at the e2e test failures?

2023-03-14 00:26 UTC, struktured commented
Checking...

On Mon, Mar 13, 2023 at 4:29 PM DrDaveD ***@***.***> wrote:

> @struktured <https://github.com/struktured> can you please look at the
> e2e test failures?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apptainer/apptainer/pull/1125#issuecomment-1466912393>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGTLITKG6ZKUWHKEAVZ6H3W357T7ANCNFSM6AAAAAAVD3TX6I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-14 21:22 UTC, DrDaveD commented
Still seeing [similar errors](https://github.com/apptainer/apptainer/actions/runs/4412070882/jobs/7744616921#step:10:599) after the latest commits.

2023-03-14 21:23 UTC, struktured commented
I got throttled by docker when testing yesterday so decided to push it
hoping it was fixed. Will continue debugging it!

On Tue, Mar 14, 2023, 5:22 PM DrDaveD ***@***.***> wrote:

> Still seeing similar errors
> <https://github.com/apptainer/apptainer/actions/runs/4412070882/jobs/7744616921#step:10:599>
> after the latest commits.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apptainer/apptainer/pull/1125#issuecomment-1468862979>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGTLIRNO3AKIW4OTSLSHLLW4DOR3ANCNFSM6AAAAAAVD3TX6I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-07 18:11 UTC, struktured commented
@DrDaveD - I can clean up the commit history but before I do that- is there anything else blocking this PR? Thanks.

2023-04-12 16:57 UTC, DrDaveD approved these changes

2023-04-12 16:58 UTC, DrDaveD commented
It looks good to me now.  After you clean up the commit history, I will merge.

2023-04-17 19:48 UTC, DrDaveD commented
Uh oh, this time the lint markdown failed.  "Headings should be surrounded by blank lines".  It doesn't like the new separater you added before "Other changes".

2023-04-17 20:14 UTC, struktured commented
Noted, will fix it after work today.

On Mon, Apr 17, 2023, 3:48 PM DrDaveD ***@***.***> wrote:

> Uh oh, this time the lint markdown failed. "Headings should be surrounded
> by blank lines". It doesn't like the new separater you added before "Other
> changes".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apptainer/apptainer/pull/1125#issuecomment-1511987708>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGTLIQ7BEQYIXPILDJBBWDXBWM77ANCNFSM6AAAAAAVD3TX6I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-18 15:42 UTC, merged

2023-04-18 15:47 UTC, DrDaveD commented
Thanks!  Please also look through the [documentation](https://apptainer.org/docs/user/main) and if changes are needed to reflect the new functionality please submit a PR at https://github.com/apptainer/apptainer-userdocs.  I expect some changes are needed to the definition file page and maybe a brief mention on the instances/running_services page.

2023-04-22 05:46 UTC, struktured commented
> Thanks! Please also look through the [documentation](https://apptainer.org/docs/user/main) and if changes are needed to reflect the new functionality please submit a PR at https://github.com/apptainer/apptainer-userdocs. I expect some changes are needed to the definition file page and maybe a brief mention on the instances/running_services page.

Will do so this weekend!