Add empty values support for template
apptainer/apptainer pull request #1734
Opened 2023-10-10 05:00 UTC by JasonYangShadow

## Description of the Pull Request (PR):

Add empty value (no value, single quote, double quote with multiple spaces)

### This fixes or addresses the following GitHub issues:

 - Fixes #1584 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

2023-10-10 13:32 UTC, DrDaveD requested changes
I think this is a simple enough upward compatible change to be in 1.2.4.  Please add a CHANGELOG entry in the 1.2.x section.

2023-10-10 18:28 UTC, DrDaveD commented
Since I'd like to finish the release today and this is the middle of your night, I added the CHANGELOG entry (after rebasing on the current main).

2023-10-10 18:53 UTC, DrDaveD approved these changes

2023-10-10 18:54 UTC, merged

2023-10-11 01:20 UTC, JasonYangShadow commented
> Since I'd like to finish the release today and this is the middle of your night, I added the CHANGELOG entry (after rebasing on the current main).

Thanks so much for the help!