add --config to `keyserver` cmd, honor optional remoteName arg, from sylabs #2035
apptainer/apptainer pull request #1852
Opened 2023-12-07 04:49 UTC by JasonYangShadow

## Description of the Pull Request (PR):

cherry pick
https://github.com/sylabs/singularity/pull/2035

which had an original description of

>  Add --config option to keyserver command. (This was available when keyservers were manipulated using the remote command, but not ported over to the keyserver command until this PR.) Utilize this flag in e2e testing of keyserver command. 
> Honor optional remoteName argument to keyserver list subcommand to list only the keyservers configured for a particular remote endpoint. Add e2e tests for this.

### This fixes or addresses the following GitHub issues:

Addresses one of the PRs in
- #1844

2023-12-07 15:14 UTC, DrDaveD requested changes
This looks fine, it just needs to be rebased on the current main to fix conflicts.

I don't think a CHANGELOG entry is needed because the `keyserver` command is new in this release.

2023-12-10 23:00 UTC, JasonYangShadow commented
> This looks fine, it just needs to be rebased on the current main to fix conflicts.
> 
> I don't think a CHANGELOG entry is needed because the `keyserver` command is new in this release.

oh, are we needing a new CHANGELOG entry? I will add one.

2023-12-12 16:52 UTC, DrDaveD commented
> > This looks fine, it just needs to be rebased on the current main to fix conflicts.
> > I don't think a CHANGELOG entry is needed because the `keyserver` command is new in this release.
> 
> oh, are we needing a new CHANGELOG entry? I will add one.

What I said it was that it was not needed, because it is already listed as a new command.   However, the existing entry actually says that the keyserver command was moved, not that was new.  So it does make sense to mention this.

However, the entry that you added is too cryptic to be helpful to users.  Please change it to
```
- Added `--config` option to`keyserver` commands.
- Honor an optional remoteName argument to the `keyserver list` command.
```

2023-12-13 17:58 UTC, DrDaveD approved these changes

2023-12-13 17:59 UTC, merged