fix: prevent scope error with docker io registry login, from sylab #2033
apptainer/apptainer pull request #1867
Opened 2023-12-18 09:39 UTC by JasonYangShadow

## Description of the Pull Request (PR):

cherry-pick https://github.com/sylabs/singularity/pull/2033

which had an original description of
> Use empty scopes for the registry ping after singularity registry login, as a "" scope is resolving to a registry level scope that gives an error when logging in to Docker Hub. May result in the credentials not being properly validated, i.e. login with bad password succeeding. However, this is the best we can do at the moment with ggcr - after extensive investigation by tri-adam and wobito.

### This fixes or addresses the following GitHub issues:

Addresses one of the PRs in
- #1844

2023-12-18 09:39 UTC, JasonYangShadow commented
merge this PR first
https://github.com/apptainer/apptainer/pull/1866

2023-12-19 19:23 UTC, cclerget approved these changes

2023-12-19 19:29 UTC, DrDaveD commented
Even though the previous PR is merged, github thinks those commits still need to be included.  Please rebase on the current main.

2023-12-20 16:41 UTC, DrDaveD requested changes
Please fix this to have just the one cherry-pick commit.

2023-12-21 05:02 UTC, JasonYangShadow commented
> Please fix this to have just the one cherry-pick commit.

thanks! done.

2023-12-21 13:10 UTC, DrDaveD approved these changes

2023-12-21 13:11 UTC, merged