Fixes #213 make dependencies for golang regarding embedded shell scripts
apptainer/apptainer pull request #222
Opened 2022-02-06 07:16 UTC by PaulCharlton

Fixes #213 make dependencies for golang regarding embedded shell scripts

2022-02-07 12:47 UTC, DrDaveD requested changes
Please rebase and remove the changes for markdownlint.

2022-02-08 06:35 UTC, PaulCharlton commented
@DrDaveD done

2022-02-08 16:50 UTC, cclerget requested changes

2022-02-08 16:50 UTC, cclerget commented on makeit/gengodep
> +  dependency_list=$( (${go} list -deps -f "${template}" -tags "${gotags}" "$@" ||true) | sort -u)
With `errexit` set, it's probably safer to remove `|| true` here to fail and not return an empty dependency list

2022-02-08 18:12 UTC, cclerget approved these changes

2022-02-08 18:12 UTC, merged