Fixed the issue when nesting `apptainer instance start` inside a container on cgroups-v2 capable host
apptainer/apptainer pull request #2220
Opened 2024-05-10 05:27 UTC by JasonYangShadow

## Description of the Pull Request (PR):

Unset `DBUS_SESSION_BUS_ADDRESS` when `systemd` is not available. 

### This fixes or addresses the following GitHub issues:

 - Fixes #2164

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

2024-05-10 05:42 UTC, JasonYangShadow commented
it looks like we are building apptainer against el7 glibc for the `install-unprivileged.sh`, where are the steps for building such rpm? 
besides, it looks like `go mod tidy` will upgrade the golang toolchain to `go1.21`.

2024-05-10 17:07 UTC, DrDaveD commented
Rebase on the current main branch to fix the rocky9 issue.  The check_source issue found a typo you need to fix.

2024-05-10 17:13 UTC, DrDaveD requested changes

2024-05-10 17:13 UTC, DrDaveD commented on internal/pkg/cgroups/manager_linux.go
> +			sylog.Warningf("Systemd is unavailabe currently, environment variable `DBUS_SESSION_BUS_ADDRESS` is set, will unset it")
Make this an Infof instead of Warningf

2024-05-10 17:13 UTC, DrDaveD commented on internal/pkg/cgroups/manager_linux.go
> +			sylog.Warningf("Systemd is unavailabe currently, environment variable `DBUS_SESSION_BUS_ADDRESS` is set, will unset it")
Let's make that message a little more user-focused as
```
Disabling cgroups because systemd is unavailable
```

2024-05-10 20:59 UTC, DrDaveD commented
> it looks like we are building apptainer against el7 glibc for the `install-unprivileged.sh`, where are the steps for building such rpm?

I'm not sure what you mean. By default install-unprivileged.sh will install el7-built rpms no matter the host OS.  When building rpms, it uses the host's glibc.

2024-05-13 07:29 UTC, JasonYangShadow commented
> > it looks like we are building apptainer against el7 glibc for the `install-unprivileged.sh`, where are the steps for building such rpm?
> 
> I'm not sure what you mean. By default install-unprivileged.sh will install el7-built rpms no matter the host OS. When building rpms, it uses the host's glibc.

Yeah, that's what I plan to do, I would like to build the el7-built rpm to test the newly added code. Are we using docker to build such rpm? (I see some scripts in `ci-docker-run`, as referred in ci.yml)

2024-05-13 14:44 UTC, DrDaveD commented
> I would like to build the el7-built rpm to test the newly added code. Are we using docker to build such rpm? (I see some scripts in `ci-docker-run`, as referred in ci.yml)

Yes, using docker.  If you're not on an el7 host you can do what ci.yml does.

2024-05-13 22:28 UTC, DrDaveD approved these changes

2024-05-13 22:29 UTC, DrDaveD commented
@JasonYangShadow are you ready for this to merge or did you want to do more testing?

2024-05-14 11:20 UTC, JasonYangShadow commented
> @JasonYangShadow are you ready for this to merge or did you want to do more testing?

yeah. I am okay with this PR.

2024-05-14 13:24 UTC, merged

2024-05-14 13:24 UTC, DrDaveD commented
Please cherry-pick to the release-1.3 branch