(WIP) refactor: containers/image -> ggcr step 2
apptainer/apptainer pull request #2500
Opened 2024-09-11 08:28 UTC by JasonYangShadow

## Description of the Pull Request (PR):

This PR brings significant changes to apptainer and breaks the ci build.

### This fixes or addresses the following GitHub issues:

 - Fixes #

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

2024-09-11 10:30 UTC, JasonYangShadow commented
@DrDaveD it looks like the ci builds scripts won't work somehow with this significant change. 
1. Unprivileged test won't work. showing errors related to `lchown invalid arguments`, which I believe is related to subuid/subgid mapping, as discussed here https://github.com/containers/podman/issues/12715, I saw that we deleted the `/etc/subuid & /etc/subgid` to trigger root-mapped namespace here https://github.com/apptainer/apptainer/blob/fe9dadd1d2c01d8ba01cc6783c447ce2f37b23ac/scripts/ci-unpriv-test#L21, it looks like this mode still does not meet the permission. If we are running in `privileged` mode, it runs good.
2. To run with minimum go version 1.21.9, it requires minimum host go version being 1.17.13, some old distros (ubuntu 20.04 & debian 11) do not meet this requirements.

2024-09-12 17:51 UTC, DrDaveD commented
When I compile this branch and try to do an unprivileged build without subuid/subgid mapping set up I get:
```
$ apptainer build image.sif image.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under the fakeroot command
INFO:    Starting build...
FATAL:   While performing build: packer failed to pack: while unpacking rootfs: error unpacking rootfs: unpack entry: run/utmp: apply hdr metadata: restore chown metadata: /scratch/tmp/build-temp-3699279536/rootfs/run/utmp: lchown /scratch/tmp/build-temp-3699279536/rootfs/run/utmp: invalid argument
```
I don't expect chown to work in this case, because it is running in only an ordinary unprivileged user namespace at that point; the fakeroot command is only used in the %post section.  That error message comes from [umoci](https://github.com/opencontainers/umoci/blob/v0.4.7/oci/layer/tar_extract.go#L119) only when `mapOptions.Rootless` is false.  So the problem is that this PR replaces in oci_unpack.c
```
if namespaces.IsUnprivileged() {
		sylog.Debugf("setting umoci rootless mode")
```
with
```
if os.Geteuid() != 0 {
```

2024-09-13 00:36 UTC, DrDaveD requested changes
Don't forgot the commit co-author

2024-09-13 00:56 UTC, JasonYangShadow commented
> When I compile this branch and try to do an unprivileged build without subuid/subgid mapping set up I get:
> 
> ```
> $ apptainer build image.sif image.def
> INFO:    User not listed in /etc/subuid, trying root-mapped namespace
> INFO:    The %post section will be run under the fakeroot command
> INFO:    Starting build...
> FATAL:   While performing build: packer failed to pack: while unpacking rootfs: error unpacking rootfs: unpack entry: run/utmp: apply hdr metadata: restore chown metadata: /scratch/tmp/build-temp-3699279536/rootfs/run/utmp: lchown /scratch/tmp/build-temp-3699279536/rootfs/run/utmp: invalid argument
> ```
> 
> I don't expect chown to work in this case, because it is running in only an ordinary unprivileged user namespace at that point; the fakeroot command is only used in the %post section. That error message comes from [umoci](https://github.com/opencontainers/umoci/blob/v0.4.7/oci/layer/tar_extract.go#L119) only when `mapOptions.Rootless` is false. So the problem is that this PR replaces in oci_unpack.c
> 
> ```
> if namespaces.IsUnprivileged() {
>         sylog.Debugf("setting umoci rootless mode")
> ```
> 
> with
> 
> ```
> if os.Geteuid() != 0 {
> ```

thanks so much for the help!

2024-09-13 13:50 UTC, DrDaveD approved these changes

2024-09-13 13:50 UTC, merged