Remove libraries from `--rocm` binds
apptainer/apptainer pull request #2606
Opened 2024-11-02 12:11 UTC by upsj

Binding these libraries from the host causes GLIBC version incompatibilities, since the ROCm libraries refer to specific, they should be provided as part of the container image.

## Description of the Pull Request (PR):

Binding these libraries from the host causes GLIBC version incompatibilities, since the ROCm libraries refer to specific, they should be provided as part of the container image.

An example for such a failure (host uses Rocky 9.4, container uses Ubuntu 18.04):

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/libnuma.so.1)
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/libelf.so.1)
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/libdrm.so.2)
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /.singularity.d/libs/libdrm_amdgpu.so.1)
```

cc @dtrudg and @tom-papatheodore

Related PR that only did half the job: https://github.com/apptainer/apptainer/pull/1622

### This fixes or addresses the following GitHub issues:

 - Fixes #1621

#### Before submitting a PR, make sure you have done the following:

- [x] Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] Make sure all commits are signed-off with `git commit -s`, see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md), if necessary according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [x] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)).
- [x] Based this PR against the appropriate branch according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [x] Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md).

2024-11-04 16:36 UTC, GodloveD commented
So, it seems like this PR is an admission that the `--rocm` option just fundamentally won't work for AMD GPUs in the way that `--nv` works for NVIDIA GPUs.  Is that an accurate assessment?  If so, why don't we just remove the `--rocm` option altogether?

2024-11-05 07:17 UTC, upsj commented
I don't think that's a necessary consequence. I would frame this more as a question of where the host-container interface should lie - for ROCm, it's easiest to mount only `/dev/dri` and `/dev/kfd`, the rest of the necessary runtime libraries gets shipped with a normal ROCm install (which is also their suggested way of starting Docker containers with ROCm GPU support), for NVIDIA, the interface lies between `/dev/nvidia*` and `libcuda.so`.

I would not remove `--rocm`, as it's a great convenience function for people getting started (and also accidentally enables Intel GPU support, since they use the same device names)

2024-11-07 21:22 UTC, GodloveD approved these changes
I'm happy to approve this PR as is.  I still don't know if this is the correct set of libraries for AMD GPUs, but I think we _do_ know that the set of libraries currently in the conf file is incorrect.  Others can at least test this if we merge it.  

Also, should this go in `CHANGELOG.md`?

2024-11-08 19:08 UTC, DrDaveD commented on etc/rocmliblist.conf
> -libcomgr.so
What if `rocm` is not installed in the container?

2024-11-08 19:25 UTC, upsj commented on etc/rocmliblist.conf
> -libcomgr.so
When would that be the case? The software needs to be compiled somehow, and for that it needs ROCm present.

2024-11-08 19:28 UTC, DrDaveD commented on etc/rocmliblist.conf
> -libcomgr.so
People can compile software on one system and run it on another, right?

2024-11-08 19:29 UTC, upsj commented on etc/rocmliblist.conf
> -librocrand.so
If the software in the container is using the libraries, then it was linked against them, so they need to be present. If it isn't, it won't matter if the libraries are not there. Beyond that, there are non-GLIBC issues caused by this behavior, see the original https://github.com/apptainer/apptainer/issues/1621

2024-11-08 19:30 UTC, upsj commented on etc/rocmliblist.conf
> -libcomgr.so
If somebody ships binaries, it's their responsibility to ship the dependencies. Otherwise how would you run the software outside a container?

2024-11-08 19:39 UTC, upsj commented on etc/rocmliblist.conf
> -libMIOpen.so
They are part of a normal `rocm` installation, not part of `amdgpu`

2024-11-08 19:44 UTC, upsj commented on etc/rocmliblist.conf
>  libhc_am.so
That's probably more of a discussion point, I haven't seen that binary in ages, I assume it doesn't exist in recent ROCm versions any more.

2024-11-08 20:16 UTC, upsj commented
To me that seems like a symptom of the ROCm integration not being used much - I started using it, and found issues with the `rocmliblist.conf` within a day just from compiling and running software.
If you compare what is being mounted for NVIDIA (driver-related libraries and files) and ROCm (driver libraries, runtime/communication/profiling/math libraries), you see that the ROCm list is much looser in its choices what to include.
I've been running software on ROCm since version 2.8, and back when the `--rocm` support was added, the software ecosystem was still very immature and changing rapidly, I wouldn't use the state back then as a blueprint for how to do things properly now.

If we want to establish a test for what should be included here, I want to propose broken backwards-compatibility plus ABI-stability:

A library should be included in the liblist if
1. it has a stable ABI (i.e. old software can still link against this library safely)
2. it is required to execute GPU applications, but GPU software can be compiled/linked without the library present OR
3. using an older version of the library from a container would not work (e.g. fail to link or execute)

If 1. is violated, including the library would cause old software to break. If 2. or 3. is violated, the library doesn't need to be included

2024-11-08 23:03 UTC, DrDaveD commented
> If we want to establish a test for what should be included here, I want to propose broken backwards-compatibility plus ABI-stability:
> 
> A library should be included in the liblist if
> 
>     1. it has a stable ABI (i.e. old software can still link against this library safely)
> 
>     2. it is required to execute GPU applications, but GPU software can be compiled/linked without the library present OR
> 
>     3. using an older version of the library from a container would not work (e.g. fail to link or execute)
> 
> 
> If 1. is violated, including the library would cause old software to break. If 2. or 3. is violated, the library doesn't need to be included

That sounds reasonable to me.

2024-11-08 23:11 UTC, DrDaveD requested changes
We do need a CHANGELOG entry.

2024-11-08 23:11 UTC, DrDaveD commented on etc/rocmliblist.conf
> -libcomgr.so
If the binaries on the host are usable then they wouldn't have to ship them.

Maybe we could allow it to work either way by making sure that if a file already exists in the container, it is not overwritten with the file from the host.  What do you think about that?

2024-12-17 16:12 UTC, DrDaveD approved these changes
We agreed in today's community meeting to go ahead and merge this as-is and if someone has a problem they can add them back in their own configuration and hopefully give us feedback.

2024-12-17 16:12 UTC, DrDaveD commented on etc/rocmliblist.conf
> -libcomgr.so
Ok we'll leave it as-is

2024-12-17 16:12 UTC, DrDaveD commented on etc/rocmliblist.conf
> -libhsa-runtime64.so
@GodloveD said this is probably analogous to the nvidia cuda runtime so that part would be more expected to be in the container.

2024-12-17 16:13 UTC, DrDaveD commented
@upsj Please rebase on the current main to pick up the new CI checks.

2024-12-18 20:58 UTC, upsj commented
@DrDaveD done, thanks for the heads-up!

2024-12-18 21:23 UTC, DrDaveD approved these changes

2024-12-18 21:23 UTC, merged