set missing platform in TestSIFAssembler and TestOCIConveyor/Packer (from sylabs #2992 and #2991)
apptainer/apptainer pull request #2655
Opened 2024-11-26 04:42 UTC by JasonYangShadow

## Description of the Pull Request (PR):

This PR re-implements the Singularity PR: 
- https://github.com/sylabs/singularity/pull/2992
- https://github.com/sylabs/singularity/pull/2991

which had an original description of
> We must provide platform when retrieving an OCI image.

### This fixes or addresses the following GitHub issues:

Addresses one of the PRs in

- https://github.com/apptainer/apptainer/issues/2546

#### Before submitting a PR, make sure you have done the following:

- [ ] Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] Make sure all commits are signed-off with `git commit -s`, see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md), if necessary according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)).
- [ ] Based this PR against the appropriate branch according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md).

2024-11-26 05:02 UTC, JasonYangShadow commented
this PR also includes the content of this PR
https://github.com/apptainer/apptainer/pull/2651

2024-11-26 17:09 UTC, DrDaveD requested changes
This contains considerably more than just those two sylabs prs.  Where did the rest of it come from?  Was there another PR that added most of it?  This seems to be adding the concept of "platform" in many places; did apptainer already have that concept? 

This seems to affect more than tests so I wonder if it needs a CHANGELOG entry.

2024-11-27 00:09 UTC, JasonYangShadow commented
> This contains considerably more than just those two sylabs prs. Where did the rest of it come from? Was there another PR that added most of it? This seems to be adding the concept of "platform" in many places; did apptainer already have that concept?
> 
> This seems to affect more than tests so I wonder if it needs a CHANGELOG entry.

Others are from my re in-implemention in order to fully support platform-related code. Platform-related code was added in earlier cherry picks/reimplementions (https://github.com/apptainer/apptainer/commit/45dc2acfdc6afc4648d24e61844f1c28c0f9793c). 
Yeah, I will add one CHANGELOG entry.

2024-11-28 09:02 UTC, dtrudg commented
Hi @JasonYangShadow @DrDaveD. There are quite a few merges of sylabs PRs that aren't trivial direct cherry picks lately. In several of these the sylabs copyright line (year) at the top of code files hasn't been updated when code has been brought in from the sylabs PR.

Would appreciate it if you can take extra care on this. Having a year range in the copyright statement is annoying, and wouldn't really be my choice - but as it's there, it needs to be kept accurate where possible.

Thanks.

2024-11-28 09:09 UTC, JasonYangShadow commented
> Hi @JasonYangShadow @DrDaveD. There are quite a few merges of sylabs PRs that aren't trivial direct cherry picks lately. In several of these the sylabs copyright line (year) at the top of code files hasn't been updated when code has been brought in from the sylabs PR.
> 
> Would appreciate it if you can take extra care on this. Having a year range in the copyright statement is annoying, and wouldn't really be my choice - but as it's there, it needs to be kept accurate where possible.
> 
> Thanks.

Sincerely thanks for the reminder! and sorry about year range copyright updates, will keep it in mind and take extra care on this. I will search and update the year range in an additional PR.

2024-11-28 09:13 UTC, dtrudg commented
> > Hi @JasonYangShadow @DrDaveD. There are quite a few merges of sylabs PRs that aren't trivial direct cherry picks lately. In several of these the sylabs copyright line (year) at the top of code files hasn't been updated when code has been brought in from the sylabs PR.
> > Would appreciate it if you can take extra care on this. Having a year range in the copyright statement is annoying, and wouldn't really be my choice - but as it's there, it needs to be kept accurate where possible.
> > Thanks.
> 
> Sincerely thanks for the reminder! and sorry about year range copyright updates, will keep it in mind and take extra care on this. I will search and update the year range in an additional PR.

Thanks. Note that you probably shouldn't just update the year range everywhere, via search / replace, as it's likely a lot of code has no recent Sylabs changes - especially as Apptainer and SingularityCE have diverged more. You probably don't want to over-attribute code to Sylabs.

It's more a thing to just try to remember when cherry-picking / manually merging from SingularityCE.

Thanks again... and don't hesitate to call us on anything you notice when we pick from Apptainer. I appreciate it's annoying to have to mess with these lines.

2024-12-06 16:06 UTC, DrDaveD approved these changes

2024-12-06 16:06 UTC, DrDaveD commented on CHANGELOG.md
> +- Refactor image arch variation using go-containerregistry's platform.
Actually now that I see the proposed CHANGELOG entry I see that it doesn't affect user experience at all so it probably should not be there.   I'll go ahead and merge it as-is though and plan on moving it to a separate "internal changes" section of the release announcement when I prepare the release and change it to describe the general internal refactoring to use go-containerregistry.

2024-12-06 16:06 UTC, merged