Add confURL & include to Arch packer
apptainer/apptainer pull request #575
Opened 2022-07-29 14:50 UTC by vejnar

Signed-off-by: vejnar <charles.vejnar@gmail.com>

## Description of the Pull Request (PR):

Building an Arch-based container uses (i) the default Pacman configuration provided by Archlinux and (ii) install the `base` metapackage. This PR allows both of these options to be configured by user by adding the following parameters: 
* `confurl`. I added this new parameter name as none of the existing ones seemed to be appropriate.
* `include`. For building package for Archlinux, only `base-devel` (not `base`) is required. With this option, Apptainer will be usable to build proper package for Arch. I reused this parameter name as it was used in the same context of package installation.

Both parameters aren't mandatory and defaults are kept unchanged.

2022-07-29 15:27 UTC, DrDaveD requested changes
This looks pretty good but will need some documentation.  Please update `examples/Arch/README.md` with info about them.  While in there please remove that erroneous reference to `Apptainer 2.3 (current development branch)`.   Also please add an entry to CHANGELOG.md new features for this.  

After merging we'll also want a PR to the [user-docs appendix](https://github.com/apptainer/apptainer-userdocs/blob/main/appendix.rst#arch-bootstrap-agent) and I'm not sure but possibly this should be mentioned in the [definition_files](https://github.com/apptainer/apptainer-userdocs/blob/main/definition_files.rst) section somewhere.

2022-07-30 01:43 UTC, vejnar commented
Thanks for your feedback. I updated README and CHANGELOG.

2022-07-30 01:44 UTC, DrDaveD commented
Looking good.  Please also add yourself to CONTRIBUTING.md

2022-07-30 01:52 UTC, vejnar commented
Ok. Done adding to CONTRIBUTORS.

2022-07-30 12:58 UTC, DrDaveD approved these changes

2022-07-30 12:58 UTC, merged