Fix --rocm option, /dev/dri/render devices needed as well
apptainer/apptainer pull request #752
Opened 2022-10-06 17:47 UTC by davidrohr

On el8 with AMD ROCm 5.1.2 (I didn't check other versions), the `/dev/dri/render*` devices are needed in addition to the `/dev/dri/card*` devices, in order for the ROCm application to access the GPU device. This PR adds the bind-mounts for these devices (in addition to the existing `/dev/kfd` and `/dev/dri/card*`) in case the `apptainer exec -c --rocm` command line options are used.

2022-10-06 20:42 UTC, DrDaveD commented
Thanks for the contribution!  Please add yourself to CONTRIBUTORS.md, add an entry in CHANGELOG.md describing the change, re-do the commit with `git -s` to satisfy the Developer Certificate of Origin, and do a force-push.

2022-10-07 16:30 UTC, DrDaveD requested changes

2022-10-07 16:30 UTC, DrDaveD commented on CHANGELOG.md
> +- `--rocm` flag in combination with `-c` / `-C` fixed by forwarging all
Please fix the "forwarging" typo.

2022-10-13 02:38 UTC, ikaneshiro approved these changes

2022-10-13 12:09 UTC, merged

2022-10-13 12:09 UTC, DrDaveD commented
@davidrohr Please submit another PR against branch release-1.1 that cherry-picks this.

2022-10-14 11:53 UTC, davidrohr commented
> @davidrohr Please submit another PR against branch release-1.1 that cherry-picks this.

Done: https://github.com/apptainer/apptainer/pull/786