remove /rootfs-* like directory when error occurs
apptainer/apptainer pull request #808
Opened 2022-10-19 08:13 UTC by JasonYangShadow

Signed-off-by: jason yang <jasonyangshadow@gmail.com>

## Description of the Pull Request (PR):

We need to clean up the $TMPDIR/rootfs-*/tmp-rootfs-* when error occurs

### This fixes or addresses the following GitHub issues:

 - Fixes #768 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

2022-10-19 21:43 UTC, DrDaveD requested changes
We don't want to remove all rootfs-* directories, just the specific one.

I ran a successful `--unsquash` with debugging on and very near the end it shows:
```
VERBOSE [U=3382,P=4289]    CleanupContainer()            Removing image tempDir /scratch/tmp/rootfs-2834231964
```
So you can do something similar to what [CleanupContainer()](https://github.com/apptainer/apptainer/blob/main/internal/pkg/runtime/engine/apptainer/cleanup_linux.go#L58) does.  It actually looks pretty complicated so it's probably worth making a function here that's also used from CleanupContainer().
```

2022-10-20 05:53 UTC, JasonYangShadow commented
> We don't want to remove all rootfs-* directories, just the specific one.
> 
> I ran a successful `--unsquash` with debugging on and very near the end it shows:
> 
> ```
> VERBOSE [U=3382,P=4289]    CleanupContainer()            Removing image tempDir /scratch/tmp/rootfs-2834231964
> ```
> 
> So you can do something similar to what [CleanupContainer()](https://github.com/apptainer/apptainer/blob/main/internal/pkg/runtime/engine/apptainer/cleanup_linux.go#L58) does. It actually looks pretty complicated so it's probably worth making a function here that's also used from CleanupContainer().

actually, it won't remove the entire rootfs-* folder, but only remove the sub-folder having the prefix `tmp-rootfs-*` generated here
https://github.com/JasonYangShadow/apptainer/blob/157eca684e499f0bd77d16cdbf4b86b2499f14a5/internal/pkg/image/unpacker/squashfs_apptainer.go#L159
anyway, the cleanup function should be optimized and called appropriately in this case.

2022-10-21 14:57 UTC, DrDaveD requested changes

2022-10-21 14:57 UTC, DrDaveD commented on internal/pkg/runtime/engine/apptainer/cleanup_linux.go
> +	apptainer "github.com/apptainer/apptainer/pkg/runtime/engine/apptainer/config"
Most other source files in this directory call this `apptainerConfig`.  I see it is inconsistent in container_linux.c.  It should probably be changed there to `apptainerConfig` too.

2022-10-21 14:57 UTC, DrDaveD commented on cmd/internal/cli/actions_linux.go
> +				defer apptainer.CleanupImageTemp(engineConfig)
sylog.Fatalf() does not return.  So just invoke this function ahead of the that call.

2022-10-21 16:43 UTC, DrDaveD commented
I'm sorry, Jason, I steered you wrong on this one.  I tried to test this and I see there's actually an attempt to remove the directory inside the `convertImage` function that isn't working.  Also there's more complication in `CleaupImageTemp` than is needed here, because it is not actually running in a separate process like it is over in the engine.  The only thing additional think that needs to be here in addition to the `RemoveAll` is a call to `types.FixPerms`.  I am working on a separate fix.

2022-10-21 16:44 UTC, closed without merging

2022-10-24 02:07 UTC, JasonYangShadow commented
> 

yes, as you explained, it looks like that it is more complex than I thought. Thanks for the info and the separate fix.