Unprivileged install for openSUSE/SUSE
apptainer/apptainer pull request #954
Opened 2022-12-21 16:11 UTC by mslacken

Adds openSUSE/SUSE distros to `tools/install-unprivileged.sh`.
Installation can be done via KOJI rpms or the rpms from the openBuild service.

2022-12-21 21:00 UTC, DrDaveD commented
Thanks!  In general this looks good.  Please fix the shellcheck ci test.  If you think the message is invalid you can always disable it with a `# shellcheck disable=` comment.  Also please re-do the commits with `git -s` to make the DCO happy.  The rocky9 failure is a known temporary failure that should be fixed soon.

Add to the usage message the fact that current suse distributions are also supported.  For the "-o" option please make it clear that it only applies to opensuse distributions.

2022-12-22 13:17 UTC, mslacken commented
Added the requested lines of explanation.

2022-12-22 13:58 UTC, DrDaveD requested changes
Please address the new failure on ubuntu in the rocky9 CI test.

And that reminds me: please add additional invocations of TEST_TYPE=unpriv in the centos7, rocky8, and rocky9 tests for the different SUSE distributions that have dockerhub containers available.

2022-12-22 13:58 UTC, DrDaveD commented on tools/install-unprivileged.sh
> +	if [ "$3" == true ]; then
If you make this kind of change please make it consistently.  I see for example below `[ "$4" = true ]`.

2022-12-22 13:58 UTC, DrDaveD commented on tools/install-unprivileged.sh
> +if test -z "$VERSION" || [[ "$KOJI" == "false" ]]; then
Let's not leave this comment, and don't make the style inconsistent by changing `[ -z` to `test`.

2022-12-22 13:58 UTC, DrDaveD commented on tools/install-unprivileged.sh
> +rmdir lib 2>/dev/null || true
Since this is my change, I think you should instead rebase on the current main and force-push.

2022-12-22 19:54 UTC, mslacken commented
Checks pass, but I had to remove tumbleweed as rolling distributions show sometimes strange errors.
I will check this more closely next year

2022-12-23 14:57 UTC, DrDaveD requested changes
If I test this with the "-o" option (on an opensuse/leap docker container) I get
```
Extracting https://download.opensuse.org/repositories/network:/cluster/openSUSE_Leap_15.4/x86_64/apptainer-1.1.2-lp154.30.17.x86_64.rpm
argument is not an RPM package
cpio: premature end of archive
Error extracting https://download.opensuse.org/repositories/network:/cluster/openSUSE_Leap_15.4/x86_64/apptainer-1.1.2-lp154.30.17.x86_64.rpm
```
I expect that since it isn't 1.1.4 that the resultant install wouldn't work, but that URL gets a 404 Not Found error and that's not right.

2023-01-04 19:04 UTC, DrDaveD commented
@mslacken Reminder, this is waiting on you.

2023-01-05 13:50 UTC, mslacken commented
Sorry for the late reply, but I was on holidays.
Basically always only *one* apptainer version is available with the open build service as older versions get deleted as soon as a new version is accepted. 
I have updated the package in the devel repo (https://build.opensuse.org/repositories/network:/cluster)  so that only 1.1.4 is now available.
I think this solves the problem.

2023-01-05 16:40 UTC, DrDaveD commented
That still doesn't quite do it.  I still get the same message.  I see that https://download.opensuse.org/repositories/network:/cluster/openSUSE_Leap_15.4/x86_64, the one being used, still has apptainer-1.1.2, but that apptainer-1.1.4 is in https://mirrorcache-us.opensuse.org/repositories/network:/cluster/15.4/x86_64/.  Does the URL need to change?  Oh I see it has already been changed in $OSREPOURL but it hasn't been changed in $EPELREPOURL.  Yes, if I make that change, it works.

I want to also make a few style changes, so I'll go ahead and push a fix to the PR branch.

2023-01-05 16:53 UTC, DrDaveD commented
Oddly, if you look at https://download.opensuse.org/repositories/network:/cluster there's no "15.4" shown, but yet if you just add it to the URL it gets you to the more up to date repository.  Something is strange there.

2023-01-05 17:15 UTC, DrDaveD commented
> Oddly, if you look at https://download.opensuse.org/repositories/network:/cluster there's no "15.4" shown, but yet if you just add it to the URL it gets you to the more up to date repository. Something is strange there.

Actually, it seems that sometimes it redirects me to https://mirrorcache-us.opensuse.org/repositories/network:/cluster and it is only then that I don't see the "15.4".  I don't understand why sometimes I get redirected and sometimes I don't.

2023-01-05 17:15 UTC, DrDaveD approved these changes

2023-01-05 17:16 UTC, DrDaveD commented
@mslacken This looks good to me now.  I will wait to merge until you tell me what you think about the additional changes I made.

2023-01-05 18:59 UTC, mslacken commented
Thanks for your additional work.

2023-01-05 20:00 UTC, merged